# Generated by Django 3.0.8 on 2020-08-26 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_app', '0002_geeksmodel_date_t'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeekLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userPassword', models.TextField()),
            ],
        ),
    ]
