# Generated by Django 3.0.8 on 2020-09-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_app', '0004_auto_20200826_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeekLogin',
        ),
    ]
