# Generated by Django 3.0.8 on 2020-09-05 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_app', '0005_delete_geeklogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('number', models.IntegerField(max_length=15)),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('postal_c', models.CharField(max_length=10)),
            ],
        ),
    ]
