# Generated by Django 3.0.8 on 2020-09-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks_app', '0006_contactmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmodel',
            old_name='fname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='date_T',
            field=models.DateTimeField(),
        ),
    ]
